[pytest]
addopts = "-m premerge"
testpaths = tests
markers   =
  premerge: marks tests as tests to run on PR (deselect with '-m "not not premerge"')
  postmerge: marks tests as tests to run postmerge (deselect with '-m "not postmerge"')
  nightly: marks tests as tests to run nightly (deselect with '-m "not nightly"')
  weekly: marks tests as tests to run nightly (deselect with '-m "not weekly"')
  serial: marks tests that should run after the parallel premerge batch
